# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\game.ui'
#
# Created: Fri Feb 21 11:26:35 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1130, 629)
        MainWindow.setMinimumSize(QtCore.QSize(1130, 629))
        MainWindow.setMaximumSize(QtCore.QSize(1130, 629))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1130, 618))
        self.centralwidget.setMaximumSize(QtCore.QSize(1130, 618))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 10, 1101, 601))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setStyleSheet(_fromUtf8("font: 12pt \"华文琥珀\";\n"
"color: rgb(170, 170, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.room = QtGui.QTreeWidget(self.widget)
        self.room.setMinimumSize(QtCore.QSize(219, 277))
        self.room.setMaximumSize(QtCore.QSize(219, 277))
        self.room.setStyleSheet(_fromUtf8("font: 11pt \"华文细黑\";\n"
"color: rgb(170, 170, 255);"))
        self.room.setObjectName(_fromUtf8("room"))
        item_0 = QtGui.QTreeWidgetItem(self.room)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.verticalLayout.addWidget(self.room)
        self.label = QtGui.QLabel(self.widget)
        self.label.setStyleSheet(_fromUtf8("font: 12pt \"华文琥珀\";\n"
"color: rgb(170, 170, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.groupTalk = QtGui.QTextEdit(self.widget)
        self.groupTalk.setMinimumSize(QtCore.QSize(219, 200))
        self.groupTalk.setMaximumSize(QtCore.QSize(219, 200))
        self.groupTalk.setStyleSheet(_fromUtf8("font: 11pt \"华文细黑\";"))
        self.groupTalk.setObjectName(_fromUtf8("groupTalk"))
        self.verticalLayout.addWidget(self.groupTalk)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupEdit = QtGui.QLineEdit(self.widget)
        self.groupEdit.setObjectName(_fromUtf8("groupEdit"))
        self.horizontalLayout.addWidget(self.groupEdit)
        self.groupSend = QtGui.QPushButton(self.widget)
        self.groupSend.setMinimumSize(QtCore.QSize(50, 22))
        self.groupSend.setMaximumSize(QtCore.QSize(50, 22))
        self.groupSend.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.groupSend.setObjectName(_fromUtf8("groupSend"))
        self.horizontalLayout.addWidget(self.groupSend)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.roomName = QtGui.QLabel(self.widget)
        self.roomName.setMinimumSize(QtCore.QSize(80, 51))
        self.roomName.setMaximumSize(QtCore.QSize(80, 51))
        self.roomName.setStyleSheet(_fromUtf8("font: 75 14pt \"微软雅黑\";\n"
"color: rgb(0, 0, 127);"))
        self.roomName.setObjectName(_fromUtf8("roomName"))
        self.verticalLayout_3.addWidget(self.roomName)
        self.inforShow = QtGui.QLabel(self.widget)
        self.inforShow.setMinimumSize(QtCore.QSize(80, 50))
        self.inforShow.setMaximumSize(QtCore.QSize(80, 50))
        self.inforShow.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"font: 75 12pt \"幼圆\";"))
        self.inforShow.setText(_fromUtf8(""))
        self.inforShow.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inforShow.setObjectName(_fromUtf8("inforShow"))
        self.verticalLayout_3.addWidget(self.inforShow)
        spacerItem = QtGui.QSpacerItem(20, 116, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.player1 = QtGui.QLabel(self.widget)
        self.player1.setMinimumSize(QtCore.QSize(84, 23))
        self.player1.setMaximumSize(QtCore.QSize(84, 23))
        self.player1.setStyleSheet(_fromUtf8("font: 13pt \"微软雅黑\";\n"
"color: rgb(170, 85, 255);"))
        self.player1.setObjectName(_fromUtf8("player1"))
        self.verticalLayout_3.addWidget(self.player1)
        spacerItem1 = QtGui.QSpacerItem(20, 196, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.score_player1 = QtGui.QLabel(self.widget)
        self.score_player1.setStyleSheet(_fromUtf8("font: 12pt \"华文琥珀\";\n"
"color: rgb(170, 170, 255);"))
        self.score_player1.setObjectName(_fromUtf8("score_player1"))
        self.verticalLayout_3.addWidget(self.score_player1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.chessBoard = QtGui.QFrame(self.widget)
        self.chessBoard.setMinimumSize(QtCore.QSize(491, 491))
        self.chessBoard.setMaximumSize(QtCore.QSize(491, 491))
        self.chessBoard.setStyleSheet(_fromUtf8("\n"
"#chessBoard {border-image: url(:/images/chessboard.png);}"))
        self.chessBoard.setObjectName(_fromUtf8("chessBoard"))
        self.horizontalLayout_4.addWidget(self.chessBoard)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(20, 244, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.player2 = QtGui.QLabel(self.widget)
        self.player2.setMinimumSize(QtCore.QSize(84, 23))
        self.player2.setMaximumSize(QtCore.QSize(84, 23))
        self.player2.setStyleSheet(_fromUtf8("font: 13pt \"微软雅黑\";\n"
"color: rgb(170, 85, 255);"))
        self.player2.setObjectName(_fromUtf8("player2"))
        self.verticalLayout_4.addWidget(self.player2)
        spacerItem3 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.score_player2 = QtGui.QLabel(self.widget)
        self.score_player2.setStyleSheet(_fromUtf8("font: 12pt \"华文琥珀\";\n"
"color: rgb(170, 170, 255);"))
        self.score_player2.setObjectName(_fromUtf8("score_player2"))
        self.verticalLayout_4.addWidget(self.score_player2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start = QtGui.QPushButton(self.widget)
        self.start.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.start.setObjectName(_fromUtf8("start"))
        self.horizontalLayout_2.addWidget(self.start)
        self.giveUp = QtGui.QPushButton(self.widget)
        self.giveUp.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.giveUp.setObjectName(_fromUtf8("giveUp"))
        self.horizontalLayout_2.addWidget(self.giveUp)
        self.undo = QtGui.QPushButton(self.widget)
        self.undo.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.undo.setObjectName(_fromUtf8("undo"))
        self.horizontalLayout_2.addWidget(self.undo)
        self.again = QtGui.QPushButton(self.widget)
        self.again.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.again.setObjectName(_fromUtf8("again"))
        self.horizontalLayout_2.addWidget(self.again)
        self.left = QtGui.QPushButton(self.widget)
        self.left.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.left.setObjectName(_fromUtf8("left"))
        self.horizontalLayout_2.addWidget(self.left)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(93, 0))
        self.label_3.setMaximumSize(QtCore.QSize(77, 16777215))
        self.label_3.setStyleSheet(_fromUtf8("font: 12pt \"华文琥珀\";\n"
"color: rgb(170, 170, 255);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.bgMusic = QtGui.QPushButton(self.widget)
        self.bgMusic.setStyleSheet(_fromUtf8("font: 9pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.bgMusic.setObjectName(_fromUtf8("bgMusic"))
        self.horizontalLayout_5.addWidget(self.bgMusic)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.scoreRank = QtGui.QListWidget(self.widget)
        self.scoreRank.setMinimumSize(QtCore.QSize(181, 251))
        self.scoreRank.setMaximumSize(QtCore.QSize(181, 251))
        self.scoreRank.setStyleSheet(_fromUtf8("font: 14pt \"华文新魏\";\n"
"color: rgb(0, 85, 0);"))
        self.scoreRank.setObjectName(_fromUtf8("scoreRank"))
        self.verticalLayout_2.addWidget(self.scoreRank)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setStyleSheet(_fromUtf8("font: 12pt \"华文琥珀\";\n"
"color: rgb(170, 170, 255);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.singleTalk = QtGui.QTextEdit(self.widget)
        self.singleTalk.setMinimumSize(QtCore.QSize(181, 192))
        self.singleTalk.setMaximumSize(QtCore.QSize(181, 192))
        self.singleTalk.setStyleSheet(_fromUtf8("font: 11pt \"华文细黑\";"))
        self.singleTalk.setObjectName(_fromUtf8("singleTalk"))
        self.verticalLayout_2.addWidget(self.singleTalk)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.singleEdit = QtGui.QLineEdit(self.widget)
        self.singleEdit.setObjectName(_fromUtf8("singleEdit"))
        self.horizontalLayout_3.addWidget(self.singleEdit)
        self.singleSend = QtGui.QPushButton(self.widget)
        self.singleSend.setMinimumSize(QtCore.QSize(41, 23))
        self.singleSend.setMaximumSize(QtCore.QSize(41, 23))
        self.singleSend.setStyleSheet(_fromUtf8("font: 12pt \"微软雅黑\";\n"
"color: rgb(24, 27, 99);"))
        self.singleSend.setObjectName(_fromUtf8("singleSend"))
        self.horizontalLayout_3.addWidget(self.singleSend)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "五子棋游戏", None))
        self.label_2.setText(_translate("MainWindow", "房间列表：", None))
        __sortingEnabled = self.room.isSortingEnabled()
        self.room.setSortingEnabled(False)
        self.room.topLevelItem(0).setText(0, _translate("MainWindow", "大厅", None))
        self.room.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "房间1", None))
        self.room.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "桌子1", None))
        self.room.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "桌子2", None))
        self.room.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "桌子3", None))
        self.room.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "桌子4", None))
        self.room.topLevelItem(0).child(0).child(4).setText(0, _translate("MainWindow", "桌子5", None))
        self.room.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "房间2", None))
        self.room.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "桌子1", None))
        self.room.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "桌子2", None))
        self.room.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "桌子3", None))
        self.room.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "桌子4", None))
        self.room.topLevelItem(0).child(1).child(4).setText(0, _translate("MainWindow", "桌子5", None))
        self.room.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "房间3", None))
        self.room.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "桌子1", None))
        self.room.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "桌子2", None))
        self.room.topLevelItem(0).child(2).child(2).setText(0, _translate("MainWindow", "桌子3", None))
        self.room.topLevelItem(0).child(2).child(3).setText(0, _translate("MainWindow", "桌子4", None))
        self.room.topLevelItem(0).child(2).child(4).setText(0, _translate("MainWindow", "桌子5", None))
        self.room.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "房间4", None))
        self.room.topLevelItem(0).child(3).child(0).setText(0, _translate("MainWindow", "桌子1", None))
        self.room.topLevelItem(0).child(3).child(1).setText(0, _translate("MainWindow", "桌子2", None))
        self.room.topLevelItem(0).child(3).child(2).setText(0, _translate("MainWindow", "桌子3", None))
        self.room.topLevelItem(0).child(3).child(3).setText(0, _translate("MainWindow", "桌子4", None))
        self.room.topLevelItem(0).child(3).child(4).setText(0, _translate("MainWindow", "桌子5", None))
        self.room.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "房间5", None))
        self.room.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "桌子1", None))
        self.room.topLevelItem(0).child(4).child(1).setText(0, _translate("MainWindow", "桌子2", None))
        self.room.topLevelItem(0).child(4).child(2).setText(0, _translate("MainWindow", "桌子3", None))
        self.room.topLevelItem(0).child(4).child(3).setText(0, _translate("MainWindow", "桌子4", None))
        self.room.topLevelItem(0).child(4).child(4).setText(0, _translate("MainWindow", "桌子5", None))
        self.room.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "群聊信息：", None))
        self.groupSend.setText(_translate("MainWindow", "发送", None))
        self.roomName.setText(_translate("MainWindow", "暂未进\n"
"入房间", None))
        self.player1.setText(_translate("MainWindow", "玩家1：", None))
        self.score_player1.setText(_translate("MainWindow", "分数：", None))
        self.player2.setText(_translate("MainWindow", "玩家2：", None))
        self.score_player2.setText(_translate("MainWindow", "分数：", None))
        self.start.setText(_translate("MainWindow", "开始", None))
        self.giveUp.setText(_translate("MainWindow", "认输", None))
        self.undo.setText(_translate("MainWindow", "悔棋", None))
        self.again.setText(_translate("MainWindow", "再来一局", None))
        self.left.setText(_translate("MainWindow", "离开", None))
        self.label_3.setText(_translate("MainWindow", "积分排行：", None))
        self.bgMusic.setText(_translate("MainWindow", "关闭背景音乐", None))
        self.label_4.setText(_translate("MainWindow", "一对一聊天：", None))
        self.singleTalk.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文细黑\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.singleSend.setText(_translate("MainWindow", "发送", None))

import resource_rc
